# Site settings
title: "nucl.ai Conference, 18-20 July 2016, Vienna/Austria."
email: team@aigamdev.com
description: >
  The largest worldwide conference about Artificial Intelligence applications
  in interactive media, training & simulations, and digital entertainment.
baseurl: ""
url: "http://nucl.ai"
twitter_username: aigamedev
github_username:  aigamedev

# Build settings
markdown: kramdown
exclude: [coffee]
